### ISSUE TITLE
Upload button on website doesn't work - timeout.

### ISSUE THREAD

**Issue by Magicrafter13** [njvsvalhalla/z2randomizer#27]
Unable to use the randomizer right now. The main site page works fine, but no matter how many times I try, I can't get it to upload the ROM or generate the modified one.

Tried another browser just in case, no difference.
![z2r](https://user-images.githubusercontent.com/29127566/136674944-38617f0a-37c7-42a4-9231-c90cb5c9b91b.png)

I know this isn't explicitly about the randomizer itself, but I'm not sure where else to put this information, and at least at a glance, it seems this repo does have files related to the website as well.

**Comment by njvsvalhalla** [comment]
Thank you for reporting - I'm going to be looking into it today or tomorrow. I think this is something to do with Azure.

**Comment by njvsvalhalla** [comment]
Actually, I did a quick check on my end. I am having what seems to be an unrelated bug that it doesn't actually download the generated rom in firefox, but it does generate it still. @Magicrafter13 are you still having issues?

**Comment by Magicrafter13** [comment]
Nope, seems to be fine now! Sorry for the late response.
